### ISSUE TITLE
New CNAME cdn2.epiclabs.io

### ISSUE THREAD

**Issue by jeoliva** [Rushmorefm/hls-proxy#10]
Needed for doing a smooth transition between old version of the server and the one working with ELB and S3. Once everything is working in cdn2.epiclabs.io we will cname cdn.epiclabs.io to the same hostname.

**Comment by jeoliva** [comment]
CNAME cdn2.epiclabs.io d3jkwy21qbpso4.cloudfront.net

**Comment by JuanS-zz** [comment]
@jeoliva done: `cdn2.upclose.me` 

I didn't do CNAME, but an A ALIAS to the Cloudfront distribution `d3jkwy21qbpso4.cloudfront.net.`
