### ISSUE TITLE
Catch errrors to Sentry

### ISSUE THREAD

**Issue by JuanS-zz** [Rushmorefm/hls-proxy#17]
key `f34d5d2c15c411e694e70242ac130001`

Settings for NodeJS
https://app.getsentry.com/upclose/hls-proxy/settings/install/node/

**Comment by jeoliva** [comment]
Done and ready in production

**Comment by JuanS-zz** [comment]
would it be possible to better identify or label the errors?

`HLS Job Failed`  `HLS Callback Failed` etc.

**Comment by fjfnaranjo-upclose** [comment]
Ideally we need two errors:
- JobFailed
- CallbackFailed

Or just JobFailed and a tag to know if it is a callback error or a ffmpeg errir or else.

Also, for comply with the Sentry workflow, the ID should be a error parameter, not part of the name. Sentry is not a log viewer, in an Exceptions registry.

**Comment by jeoliva** [comment]
Done. Five type of errors:
- HLS Callback Failed.
- HLS Job Failed. Job failed while streaming was running.
- HLS initialization error. Job failed in the initialization process -> tokbox m3u8 was never available.
- HLS initialization error (FFMPEG).  Job failed when trying to start ffmpeg process -> tokbox m3u8 was available although it doesn't contain a valid HLS stream
- HLS S3 failed. Error while uploading files to S3.

Sounds ok?

**Comment by fjfnaranjo-upclose** [comment]
Sound nice.

Maybe we should keep the exception names camel case with no spaces. And we do not need the "HLS" part because we always know the exception origin. And keeping the same suffix for all names is better: CallbackError InitializationError S3Error 'or' CallbackFailed InitializationFailed S3Failed

**Comment by jeoliva** [comment]
Makes sense, done and committed. README updated with errors info.
