### ISSUE TITLE
Send "loading" stream while waiting for Tokbox hls

### ISSUE THREAD

**Issue by JuanS-zz** [Rushmorefm/hls-proxy#21]
and call back to upclose API as soon as the loading stream not available, no need to wait for tokbox signal.

if possible the stream should show tokbox live without need to reload the player

**Comment by JuanS-zz** [comment]
estimation pending

**Comment by jeoliva** [comment]
I have found out a way for getting this working with Tumblr player although it is pretty tight to current Tumblr player config. The idea behind this is taking advantage of Tumblr player being configured with "auto loop" so it play a stream one time after the other. 

This will work, impact is very low in our end, dev time is low (1 day is more than enough for doing this, test and deploy). The only inconvenient is this solution is tighly coupled to current player config. If Tumblr player deactivates loop mode, then "Loading video" will be shown eternally and for every stream.
