### ISSUE TITLE
Test Opentok Cloudfront migration

### ISSUE THREAD

**Issue by JuanS-zz** [Rushmorefm/hls-proxy#22]
We can start with the DEV environment

**Comment by jeoliva** [comment]
Tokbox is going to enable a new api key for testing this "feature" as it requires changing configs, client sdk's, etc

**Comment by jeoliva** [comment]
regarding stability there are no differences comparing with Akamai delivery. Good point is they have reduced segment length to 3 seconds so latency has been highly reduced (around 20-25 seconds). 

Stability continues to be a problem. I have detected some issues in the way they are encoding the HLS streams and they are working on a fix. First version of a fix was put in place on last Friday. Today evening  will have a meeting with them to review changes.
